// Verify every App Store Connect text field in docs/APP-STORE-LISTING.md fits
// its limit.
//
// Why this exists: ASC silently truncates or refuses on paste, and a field
// that is two characters over is discovered at the worst possible moment. The
// counts in that document are generated by this script rather than eyeballed.
//
// Apple counts UTF-16 code units, which is what JS `.length` gives — so an
// emoji or an accented character can cost more than it looks. Counting with
// anything else (bytes, grapheme clusters) would report a number ASC disagrees
// with.
//
// Usage:  node scripts/check-listing.mjs

import { readFileSync } from 'node:fs'

const DOC = 'docs/APP-STORE-LISTING.md'
const src = readFileSync(DOC, 'utf8')

/** Pull the first fenced block that follows a `## n. <name>` heading. */
function block(headingFragment) {
  const h = src.indexOf(headingFragment)
  if (h === -1) return null
  const open = src.indexOf('```', h)
  if (open === -1) return null
  const start = src.indexOf('\n', open) + 1
  const close = src.indexOf('```', start)
  if (close === -1) return null
  return src.slice(start, close).replace(/\n$/, '')
}

const FIELDS = [
  { name: 'App Name', heading: '## 1. App Name', limit: 30 },
  { name: 'Subtitle', heading: '## 2. Subtitle', limit: 30 },
  { name: 'Promotional Text', heading: '## 3. Promotional Text', limit: 170 },
  { name: 'Keywords', heading: '## 4. Keywords', limit: 100 },
  { name: 'Description', heading: '## 5. Description', limit: 4000 },
  { name: 'Review Notes', heading: '## 8. App Review Information', limit: 4000 },
]

let bad = 0
for (const f of FIELDS) {
  const text = block(f.heading)
  if (text === null) {
    console.log(`MISSING  ${f.name} — no fenced block after "${f.heading}"`)
    bad++
    continue
  }
  const n = text.length
  const ok = n <= f.limit
  if (!ok) bad++
  console.log(
    `${ok ? 'ok  ' : 'OVER'}  ${f.name.padEnd(18)} ${String(n).padStart(4)} / ${f.limit}` +
      (ok ? `  (${f.limit - n} spare)` : `  — ${n - f.limit} OVER`),
  )
}

// Keywords have their own rules beyond length.
const kw = block('## 4. Keywords')
if (kw) {
  console.log('\n--- keywords ---')
  if (/,\s/.test(kw)) {
    console.log('  WARN  a space follows a comma; each one wastes a character')
    bad++
  } else {
    console.log('  ok    no spaces after commas')
  }
  const terms = kw.split(',').map((t) => t.trim().toLowerCase()).filter(Boolean)
  const dupes = terms.filter((t, i) => terms.indexOf(t) !== i)
  console.log(dupes.length ? `  WARN  duplicate terms: ${dupes.join(', ')}` : '  ok    no duplicate terms')
  if (dupes.length) bad++

  // Apple indexes name + subtitle + keywords together; repeating a word that
  // is already in the name or subtitle spends the budget twice for nothing.
  const nameWords = ((block('## 1. App Name') || '') + ' ' + (block('## 2. Subtitle') || ''))
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter((w) => w.length > 2)
  const overlap = terms.filter((t) => nameWords.includes(t))
  console.log(
    overlap.length
      ? `  WARN  already in the name/subtitle, so wasted here: ${overlap.join(', ')}`
      : '  ok    no overlap with name or subtitle',
  )
  if (overlap.length) bad++
}

console.log(bad === 0 ? '\nEvery field fits.' : `\n${bad} problem(s) to fix before pasting into ASC.`)
process.exitCode = bad === 0 ? 0 : 1
